---

# Note: this role does not actually deploy templates
#       in order to do that, execute the "deploy.yml" Playbook in the same directory
#
# You must specify $bind9_data


# fail if it's not a Debian based system
- name: Check OS (bind9)
  fail: msg="Not a Debian based system!"
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'


# the following code is for debugging zone updates (quickly)

#- debug: msg="{{bind_key_templates}}"
#- debug: msg="{{bind_key_items.results}}"
#
#- name:
#  #- debug: msg="{{ item }}"
#  include: "{{ role_path }}/tasks/update-zone.yml zone_file={{ item }}"
##  with_items: bind_key_templates
#  with_fileglob:
#    - "{{ role_path }}/templates/zones/*.zone"
#- fail: msg="Stop"


- name: check if data directory for local bind9 data exists
  become: no
  local_action: stat path="{{ template }}"
  register: bind9_data_exists

- name: Stop here because no local data directory exists
  fail: msg="Please create a local data directory first ({{ template }})"
  when: bind9_data_exists.stat.exists == False or bind9_data_exists.stat.isdir == False


- name: check if keys directory for local bind9 data exists
  become: no
  local_action: stat path="{{ template }}/keys"
  register: bind9_data_keys_exists

- name: Stop here because no local keys directory exists
  fail: msg="Please create a local keys directory first ({{ template }}/keys)"
  when: bind9_data_keys_exists.stat.exists == False or bind9_data_keys_exists.stat.isdir == False


- name: check if zones directory for local bind9 data exists
  become: no
  local_action: stat path="{{ template }}/zones"
  register: bind9_data_zones_exists

- name: Stop here because no local zones directory exists
  fail: msg="Please create a local zones directory first ({{ template }}/zones)"
  when: bind9_data_zones_exists.stat.exists == False or bind9_data_zones_exists.stat.isdir == False


- name: check if zone-data directory for local bind9 data exists
  become: no
  local_action: stat path="{{ template }}/zone-data"
  register: bind9_data_zone_data_exists

- name: Stop here because no local zone-data directory exists
  fail: msg="Please create a local zone-data directory first ({{ template }}/zone-data)"
  when: bind9_data_zone_data_exists.stat.exists == False or bind9_data_zone_data_exists.stat.isdir == False


# update package cache - required for any new software installation
- name: Update apt cache
  apt:
    update_cache: yes
  changed_when: false


# install bind9 packages (Debian/Ubuntu)
- name: basic packages
  apt:
    state: present
    name:
      - aptitude
      - bind9
      - bind9-host
      - bind9utils


- name: check if logfile already exists
  stat:
    path: /var/log/bind.log
  register: bind9_logfile


- name: create bind9 logfile
  file:
    path: /var/log/bind.log
    owner: bind
    group: bind
    mode: 0640
    state: '{{ "file" if bind9_logfile.stat.exists else "touch" }}'


- name: /etc/apparmor.d/local/usr.sbin.named
  copy:
    src: "{{ template }}/apparmor_usr.sbin.named.j2"
    dest: /etc/apparmor.d/local/usr.sbin.named
    owner: root
    group: root
    mode: 0644
  notify:
    - reload apparmor bind9 profile
    - reload bind9


- name: create directory for dynamic updates
  file:
    path: /etc/bind/dynamic-updates
    state: directory
    owner: bind
    group: bind
    mode: 0700


- name: check if local copy of named.conf.options.j2 exists
  become: no
  local_action: stat path="{{ template }}/named.conf.options.j2"
  register: named_conf_options_exists


- block:
  # this block just emits a note that a local named.conf.options.j2 is missing
  - name: /etc/bind/named.conf.options.j2 does not exist
    debug: msg="Create {{ template }}/named.conf.options.j2 first!"


  - name: Create named.conf.options.j2 from template
    debug: msg="You can use {{ template }}/named.conf.options.j2 as template"


  - name: Stop here because no local named.conf.options.j2 exists
    fail: msg="Please provide local named.conf.options.j2 first"

  when: named_conf_options_exists.stat.exists == False


- name: check if local copy of named.conf.local.j2 exists
  become: no
  local_action: stat path="{{ template }}/named.conf.local.j2"
  register: named_conf_local_exists


- block:
  # this block just emits a note that a local named.conf.local.j2 is missing
  - name: /etc/bind/named.conf.local.j2 does not exist
    debug: msg="Create {{ template }}/named.conf.local.j2 first!"


  - name: Create named.conf.local.j2 from template
    debug: msg="You can use {{ template }}/named.conf.local.j2.template as template"


  - name: Stop here because no local named.conf.local.j2 exists
    fail: msg="Please provide local named.conf.local.j2 first"

  when: named_conf_local_exists.stat.exists == False



- meta: flush_handlers
